# Change these first
owner: drasyl-overlay # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Super-Peer Frankfurt 1
    check: "tcp-ping"
    url: sp-fra1.drasyl.org
    port: 22527
  - name: Super-Peer Nuremberg 2
    check: "tcp-ping"
    url: sp-nbg2.drasyl.org
    port: 22527

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.drasyl.org
  # baseUrl: /your-repo-name
  logoUrl: https://docs.drasyl.org/assets/img/drasyl.svg
  name: drasyl Status
  introTitle: "drasyl's super-peers status page"
  introMessage: "**drasyl** is a general-purpose overlay network framework for rapid development of distributed P2P applications."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://drasyl.org
   - title: Docs
      href: https://docs.drasyl.org
    - title: GitHub
      href: https://github.com/drasyl-overlay/drasyl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
